#!/bin/sh

choice="$(
    printf '%s\n' \
        'Lock' \
        'Logout' \
        'Reboot' \
        'Power Off' |
    fuzzel --dmenu --prompt='Power: '
)"

case "$choice" in
    'Lock')
        swaylock -f
        ;;
    'Logout')
        niri msg action quit
        ;;
    'Reboot')
        doas /usr/bin/reboot
        ;;
    'Power Off')
        doas /usr/bin/poweroff
        ;;
esac
