import os

NEWSBLUR_URL = os.getenv("NEWSBLUR_URL", "https://cinderace.tailfe05b.ts.net")
SESSION_COOKIE_DOMAIN = None
SECRET_KEY = os.environ["NEWSBLUR_SECRET_KEY"]
MCP_OAUTH_CLIENT_SECRET = os.environ["MCP_OAUTH_CLIENT_SECRET"]

AUTO_PREMIUM = True
AUTO_PREMIUM_NEW_USERS = True
AUTO_PREMIUM_ARCHIVE_NEW_USERS = True
AUTO_PREMIUM_PRO_NEW_USERS = False
AUTO_ENABLE_NEW_USERS = True
ENFORCE_SIGNUP_CAPTCHA = False

# Archive-tier stories and hashes are retained for roughly 1,000 years.
DAYS_OF_UNREAD_ARCHIVE = 365000
DAYS_OF_STORY_HASHES_ARCHIVE = DAYS_OF_UNREAD_ARCHIVE

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
GOOGLE_GEMINI_API_KEY = os.getenv("GOOGLE_GEMINI_API_KEY", "")
ASK_AI_MODEL = os.getenv("ASK_AI_MODEL", "gpt-5-mini")
BRIEFING_MODEL = os.getenv("BRIEFING_MODEL", "gpt-5-mini")
