include luna.conf

font_family Berkeley Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13.0
symbol_map U+E000-U+E00A,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono

window_padding_width 3 10
background_opacity 1
cursor_blink_interval 0
cursor_shape beam

enable_audio_bell no
shell_integration no-cursor
allow_remote_control yes
listen_on unix:@mykitty
enabled_layouts splits,stack,tall,fat,grid
map_timeout 1.5

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right

map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+l

map alt+h kitten relative_resize.py left  3
map alt+j kitten relative_resize.py down  3
map alt+k kitten relative_resize.py up    3
map alt+l kitten relative_resize.py right 3

map --when-focus-on var:IS_NVIM alt+h
map --when-focus-on var:IS_NVIM alt+j
map --when-focus-on var:IS_NVIM alt+k
map --when-focus-on var:IS_NVIM alt+l

map ctrl+b>ctrl+b send_text all \x02

map ctrl+b>c new_tab_with_cwd
map ctrl+b>n next_tab
map ctrl+b>p previous_tab
map ctrl+b>tab goto_tab 0
map ctrl+b>w select_tab
map ctrl+b>comma set_tab_title
map ctrl+b>ampersand close_tab
map ctrl+b>1 goto_tab 1
map ctrl+b>2 goto_tab 2
map ctrl+b>3 goto_tab 3
map ctrl+b>4 goto_tab 4
map ctrl+b>5 goto_tab 5
map ctrl+b>6 goto_tab 6
map ctrl+b>7 goto_tab 7
map ctrl+b>8 goto_tab 8
map ctrl+b>9 goto_tab 9
map ctrl+b>shift+comma move_tab_backward
map ctrl+b>shift+period move_tab_forward

map ctrl+b>shift+backslash launch --location=vsplit --cwd=current
map ctrl+b>minus launch --location=hsplit --cwd=current
map ctrl+b>shift+5 launch --location=vsplit --cwd=current
map ctrl+b>shift+apostrophe launch --location=hsplit --cwd=current
map ctrl+b>x close_window
map ctrl+b>q focus_visible_window
map ctrl+b>h neighboring_window left
map ctrl+b>j neighboring_window down
map ctrl+b>k neighboring_window up
map ctrl+b>l neighboring_window right
map ctrl+b>semicolon neighboring_window previous
map ctrl+b>o next_window
map ctrl+b>shift+o move_window_forward
map ctrl+b>m detach_window ask
map ctrl+b>shift+1 detach_window new

map ctrl+b>space next_layout
map ctrl+b>z toggle_layout stack

map --new-mode resize --timeout 5.0 ctrl+b>r
map --mode resize h resize_window narrower 3
map --mode resize j resize_window taller 3
map --mode resize k resize_window shorter 3
map --mode resize l resize_window wider 3
map --mode resize equal resize_window reset
map --mode resize esc pop_keyboard_mode
map --mode resize enter pop_keyboard_mode

map ctrl+b>left_bracket show_scrollback
map ctrl+b>right_bracket paste_from_clipboard
map ctrl+b>b launch --allow-remote-control kitten broadcast
map ctrl+b>colon load_config_file
map ctrl+b>shift+slash kitten command_palette

map ctrl+b>s goto_session
map ctrl+b>shift+s save_as_session --use-foreground-process --base-dir ~/.local/share/kitty/sessions
