[background]
path = "/usr/local/share/regreet/warm-skies.jpg"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Bibata-Modern-Classic"
font_name = "Berkeley Mono 13"
icon_theme_name = "breeze-dark"
theme_name = "Adwaita"

[commands]
reboot = [ "loginctl", "reboot" ]
poweroff = [ "loginctl", "poweroff" ]
