context.objects = [
    {
        factory = adapter
        args = {
            factory.name = support.null-audio-sink
            node.name = brave_share
            node.nick = "Brave Share"
            node.description = "Brave Share"
            media.class = Audio/Sink
            audio.position = [ FL FR ]
            monitor.channel-volumes = true
            object.linger = true
        }
    }
]
