pulse.rules = [
    {
        matches = [
            { application.process.binary = "brave" }
        ]
        actions = {
            update-props = {
                target.object = "brave_share"
            }
        }
    }
]
