#!/bin/bash

SELECTION="$(printf "Suspend\nLog out\nReboot\nShutdown" | rofi -dmenu -p "Power Menu: ")"

case $SELECTION in
	*"Suspend")
		systemctl suspend;;
	*"Log out")
		niri msg action quit --skip-confirmation;;
	*"Reboot")
		systemctl reboot;;
	*"Shutdown")
		systemctl poweroff;;
esac
