monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-Topping_DX5_II.*"
      }
    ]
    actions = {
      update-props = {
        device.nick = "Topping DX5 II"
        device.description = "Topping DX5 II"
        api.acp.auto-ports-wait = true
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_output.usb-Topping_DX5_II.*"
      }
    ]
    actions = {
      update-props = {
        node.nick = "Topping DX5 II"
        node.description = "Topping DX5 II"
        audio.rate = 0
        audio.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]
        api.alsa.multi-rate = true
      }
    }
  }
]
