#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Install tools from Homebrew through Brewfile
echo "> brew bundle"
brew bundle --file ~/.dotfiles/Brewfile

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
